services:
  beets-jar:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: beets-jar
    restart: unless-stopped
    ports:
      - "7734:7734"
    environment:
      - BEETSDIR=/app/data
    volumes:
      - ./dev/data:/app/data
      - ./dev/music:/music
      - ./beetsplug:/custom-plugins
      - ./dev/downloads:/import/downloads
      # FOR DEVELOPMENT ONLY
      - ./app:/app/app
    command: sh -c "uv sync --frozen --group dev && uvicorn app.main:app --host 0.0.0.0 --port 7734 --reload --reload-dir /app/app"
